In [1]:
import pandas as pd

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movie_list=movies.merge(credits,on='title')

In [4]:
movie_list.shape

(4809, 23)

In [5]:
movie_list.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
movie_list.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [7]:
movie_list.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count,movie_id
count,4.809000e+03,4809.000000,4809.000000,4.809000e+03,4807.000000,4809.000000,4809.000000,4809.000000
mean,2.902780e+07,57120.571429,21.491664,8.227511e+07,106.882255,6.092514,690.331670,57120.571429
std,4.070473e+07,88653.369849,31.803366,1.628379e+08,22.602535,1.193989,1234.187111,88653.369849
min,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,5.000000
25%,7.800000e+05,9012.000000,4.667230,0.000000e+00,94.000000,5.600000,54.000000,9012.000000
50%,1.500000e+07,14624.000000,12.921594,1.917000e+07,103.000000,6.200000,235.000000,14624.000000
75%,4.000000e+07,58595.000000,28.350529,9.291317e+07,118.000000,6.800000,737.000000,58595.000000
max,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000,459488.000000

In [8]:
movie_list.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

In [9]:
movie_list=movie_list.drop(columns=['homepage','original_language','original_title','production_countries','release_date','runtime','spoken_languages','status','vote_count','movie_id','popularity','revenue','vote_average','budget'])

movi

# Task 2

In [10]:
movie_list.head(2)

,genres,id,keywords,overview,production_companies,tagline,title,cast,crew
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""name"": ""Ingenious Film Partners"", ""id"": 289...",Enter the World of Pandora.,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [11]:
import ast

In [12]:
def extract_names (col):
    L=[]
    for i in ast.literal_eval(col):
        L.append(i['name'])
    return " ".join(L)

In [13]:
def extract_cast_names(col):
    L=[]
    for i in ast.literal_eval(col):
        L.append(i['name'])
    return L

In [14]:
def extract_director(col):
    L=[]
    for i in ast.literal_eval(col):
        if i['job']== 'Director':
            L.append(i['name'])
    return L

In [15]:
movie_list['genres'] = movie_list['genres'].apply(extract_names)
movie_list['keywords'] = movie_list['keywords'].apply(extract_names)
movie_list['cast'] =movie_list['cast'].apply(extract_cast_names)
movie_list['production_companies'] = movie_list['production_companies'].apply(extract_names)
movie_list['crew'] = movie_list['crew'].apply(extract_director)

In [16]:
movie_list.head(2)

,genres,id,keywords,overview,production_companies,tagline,title,cast,crew
0,Action Adventure Fantasy Science Fiction,19995,culture clash future space war space colony so...,"In the 22nd century, a paraplegic Marine is di...",Ingenious Film Partners Twentieth Century Fox ...,Enter the World of Pandora.,Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,Adventure Fantasy Action,285,ocean drug abuse exotic island east india trad...,"Captain Barbossa, long believed to be dead, ha...",Walt Disney Pictures Jerry Bruckheimer Films S...,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,"[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]

In [17]:
movie_list['crew']=movie_list['crew'].apply(lambda x: ''.join(x))
movie_list['cast']=movie_list['cast'].apply(lambda x: ' '.join(x))

In [18]:
movie_list.head(2)

,genres,id,keywords,overview,production_companies,tagline,title,cast,crew
0,Action Adventure Fantasy Science Fiction,19995,culture clash future space war space colony so...,"In the 22nd century, a paraplegic Marine is di...",Ingenious Film Partners Twentieth Century Fox ...,Enter the World of Pandora.,Avatar,Sam Worthington Zoe Saldana Sigourney Weaver S...,James Cameron
1,Adventure Fantasy Action,285,ocean drug abuse exotic island east india trad...,"Captain Barbossa, long believed to be dead, ha...",Walt Disney Pictures Jerry Bruckheimer Films S...,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,Johnny Depp Orlando Bloom Keira Knightley Stel...,Gore Verbinski

In [19]:
movie_list['tags'] = movie_list['genres']+" "+movie_list['keywords']+ " " + movie_list['overview'] +" "+ movie_list['production_companies']+" "+movie_list['tagline']+" " +movie_list['cast']+" " + movie_list['crew']

In [20]:
movie_list=movie_list.drop(columns=[ 'genres', 'keywords', 'overview',
       'production_companies', 'tagline',
       'cast', 'crew'])

In [21]:
movie_list.head(2)

,id,title,tags
0,19995,Avatar,Action Adventure Fantasy Science Fiction cultu...
1,285,Pirates of the Caribbean: At World's End,Adventure Fantasy Action ocean drug abuse exot...

now lets convert the text to lower case

In [22]:
movie_list['tags'] = movie_list['tags'].astype('category')

In [23]:
movie_list['tags'].head(2)

0    Action Adventure Fantasy Science Fiction cultu...
1    Adventure Fantasy Action ocean drug abuse exot...
Name: tags, dtype: category
Categories (3965, object): ['  Surprise parties rarely go well. This one i..., '  The story of Lehi and his wife Sariah and t..., '  When ambitious New York attorney Sam is sen..., 'Action  Former Green Beret Louis Stevens retu..., ..., 'Western saloon hero liberation of prisoners t..., 'Western sheriff aging billy the kid lawlessne..., 'Western showdown bounty bounty hunter loss of..., 'Western texas dangerous kansas cattle drive r...]

lets apply lowercasing to the text

In [24]:
movie_list['tags']= movie_list['tags'].apply(lambda x: x.lower())

In [25]:
movie_list.head(2)

,id,title,tags
0,19995,Avatar,action adventure fantasy science fiction cultu...
1,285,Pirates of the Caribbean: At World's End,adventure fantasy action ocean drug abuse exot...

In [26]:
import re

lets remove puctuation

In [27]:
def remove_puncuation(text):
    return re.sub(r'[^\w\s]',"",text)

In [28]:
movie_list['tags']=movie_list['tags'].apply(remove_puncuation)

In [29]:
movie_list['tags']

0       action adventure fantasy science fiction cultu...
1       adventure fantasy action ocean drug abuse exot...
2       action adventure crime spy based on novel secr...
3       action crime drama thriller dc comics crime fi...
4       action adventure science fiction based on nove...
                              ...
4804    action crime thriller united statesmexico barr...
4805    comedy romance  a newlywed couples honeymoon i...
4806                                                  NaN
4807      when ambitious new york attorney sam is sent...
4808                                                  NaN
Name: tags, Length: 4809, dtype: category
Categories (3965, object): ['  surprise parties rarely go well this one is..., '  the story of lehi and his wife sariah and t..., '  when ambitious new york attorney sam is sen..., 'action  former green beret louis stevens retu..., ..., 'western saloon hero liberation of prisoners t..., 'western sheriff aging billy the kid lawlessne..., 'western showdown bounty bounty hunter loss of..., 'western texas dangerous kansas cattle drive r...]

now lets remove stop words

In [30]:
from nltk.corpus import stopwords

In [31]:
stop =set(stopwords.words('english'))

In [32]:
stop

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [33]:
movie_list.head(2)

,id,title,tags
0,19995,Avatar,action adventure fantasy science fiction cultu...
1,285,Pirates of the Caribbean: At World's End,adventure fantasy action ocean drug abuse exot...

In [34]:
def remove_stopword(text):
    li =[]
    for word in text.split():
        if word not in stop:
            li.append(word)
    return " ".join(li)

In [35]:
movie_list['tags']=movie_list['tags'].apply(remove_stopword)

In [36]:
movie_list['tags'][0]

'action adventure fantasy science fiction culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind soul 3d 22nd century paraplegic marine dispatched moon pandora unique mission becomes torn following orders protecting alien civilization ingenious film partners twentieth century fox film corporation dune entertainment lightstorm entertainment enter world pandora sam worthington zoe saldana sigourney weaver stephen lang michelle rodriguez giovanni ribisi joel david moore cch pounder wes studi laz alonso dileep rao matt gerald sean anthony moran jason whyte scott lawrence kelly kilgour james patrick pitt sean patrick murphy peter dillon kevin dorman kelson henderson david van horn jacob tomuri michael blainrozgay jon curry luke hawker woody schultz peter mensah sonia yee jahnel curfman ilram choi kyla warren lisa roumain debra wilson chris mala taylor kibby jodie landau julie lamm cullen b madden joseph brady madden frankie torres austin wilson sara wilson tamica washingtonmiller lucy briant nathan meister gerry blair matthew chamberlain paul yates wray wilson james gaylyn melvin leno clark iii carvon futrell brandon jelkes micah moch hanniyah muhammad christopher nolen christa oliver april marie thomas bravita threatt colin bleasdale mike bodnar matt clayton nicole dionne jamie harrison allan henry anthony ingruber ashley jeffery dean knowsley joseph mikahunt terry notary kai pantano logan pithyou stuart pollock raja gareth ruck rhian sheehan j storm jodie taylor alicia velabailey richard whiteside nikie zambo julene renee james cameron'

here you can see that the stop words are gone

now lets handle the missing values

In [37]:
movie_list.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      4809 non-null   int64
 1   title   4809 non-null   object
 2   tags    3965 non-null   category
dtypes: category(1), int64(1), object(1)
memory usage: 244.7+ KB

In [38]:
movie_list.isna().sum()

id         0
title      0
tags     844
dtype: int64

In [39]:
movie_list.dropna(inplace=True)

In [40]:
movie_list.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3965 entries, 0 to 4807
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      3965 non-null   int64
 1   title   3965 non-null   object
 2   tags    3965 non-null   category
dtypes: category(1), int64(1), object(1)
memory usage: 260.7+ KB

here you can see all the missing values are eradicated

In [41]:
clean_text = movie_list

# task 3

In [42]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [43]:
tf = TfidfVectorizer(max_features=5000,ngram_range=(1,2))

In [44]:
matrix =tf.fit_transform(clean_text['tags'])

In [45]:
matrix.shape

(3965, 5000)

# task 4

In [46]:
from sklearn.metrics.pairwise import cosine_similarity

In [47]:
similarities = cosine_similarity(matrix)

In [48]:
similarities

array([[1.        , 0.03905699, 0.03143101, ..., 0.01613109, 0.00370634,
        0.01446369],
       [0.03905699, 1.        , 0.02654661, ..., 0.0225556 , 0.        ,
        0.02448087],
       [0.03143101, 0.02654661, 1.        , ..., 0.02891776, 0.        ,
        0.02809429],
       ...,
       [0.01613109, 0.0225556 , 0.02891776, ..., 1.        , 0.        ,
        0.00806019],
       [0.00370634, 0.        , 0.        , ..., 0.        , 1.        ,
        0.0079465 ],
       [0.01446369, 0.02448087, 0.02809429, ..., 0.00806019, 0.0079465 ,
        1.        ]], shape=(3965, 3965))

cosine similarity is used to relate one movies to another in an multi dimensional space because all the embeddings of the movies are stored in the multi dimensional space

# task 5

In [49]:
movie_list['title']

0                                         Avatar
1       Pirates of the Caribbean: At World's End
2                                        Spectre
3                          The Dark Knight Rises
4                                    John Carter
                          ...
4801                                        Bang
4802                                      Primer
4804                                 El Mariachi
4805                                   Newlyweds
4807                            Shanghai Calling
Name: title, Length: 3965, dtype: object

In [50]:
def recommend(item_name, top_n=5):
    movie_index = movie_list[movie_list['title']==item_name].index[0]
    recommendation = similarities[movie_index]
    movie_indices = sorted(enumerate(recommendation),reverse=True,key=lambda x: x[1])[1:top_n]
    for movie_index, similar in movie_indices:
        print(movie_list.iloc[movie_index]['title'])

In [51]:
recommend('Pirates of the Caribbean: At World\'s End')

Pirates of the Caribbean: Dead Man's Chest
Pirates of the Caribbean: The Curse of the Black Pearl
Pirates of the Caribbean: On Stranger Tides
G-Force

In [52]:
recommend('Iron Man')

The Last Emperor
The Mummy Returns
The Forbidden Kingdom
The Painted Veil

In [53]:
recommend('The Forbidden Kingdom')

Ninja Assassin
Nighthawks
Better Luck Tomorrow
The Fast and the Furious: Tokyo Drift

In [54]:
import pickle

In [55]:
with open('movies.pickle','wb') as f:
    pickle.dump(movie_list,f)

In [56]:
import joblib

In [59]:
with open('similarities.joblib','wb') as f:
    joblib.dump(f,similarities,compress=6)

ValueError: Second argument should be a filename or a file-like object, [[1.         0.03905699 0.03143101 ... 0.01613109 0.00370634 0.01446369]
 [0.03905699 1.         0.02654661 ... 0.0225556  0.         0.02448087]
 [0.03143101 0.02654661 1.         ... 0.02891776 0.         0.02809429]
 ...
 [0.01613109 0.0225556  0.02891776 ... 1.         0.         0.00806019]
 [0.00370634 0.         0.         ... 0.         1.         0.0079465 ]
 [0.01446369 0.02448087 0.02809429 ... 0.00806019 0.0079465  1.        ]] (type <class 'numpy.ndarray'>) was given.